# Generated by Django 3.2.8 on 2021-10-07 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, validators=[django.core.validators.URLValidator()])),
                ('url_hash', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True)),
                ('short_url', models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
