# Generated by Django 3.2.8 on 2021-10-25 19:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, validators=[django.core.validators.URLValidator()], verbose_name='url')),
                ('scheme', models.CharField(blank=True, max_length=20, null=True)),
                ('hostname', models.CharField(blank=True, max_length=50, null=True)),
                ('url_hash', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, verbose_name='url-hash')),
                ('short_url', models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.URLValidator()], verbose_name='short-url')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
