# Generated by Django 3.2.8 on 2021-10-13 11:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortener', '0002_url_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.URLValidator()], verbose_name='short-url'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=250, validators=[django.core.validators.URLValidator()], verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_hash',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, verbose_name='url-hash'),
        ),
        migrations.AlterField(
            model_name='url',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
