# Generated by Django 3.2.8 on 2021-10-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20211013_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='hostname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='scheme',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
